# Generated by Django 4.0.4 on 2022-04-18 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedPantryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_pct_full', models.FloatField()),
                ('last_pct_full', models.FloatField(null=True)),
                ('last_restock_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'estimated_pantry_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=500)),
                ('deplete_pct_per_day', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('overflow_dropoff', models.TextField(help_text="Where to drop off items that don't fit in the pantry", max_length=500)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('slug', models.SlugField()),
                ('type', models.TextField(choices=[('fridge', 'Fridge'), ('pantry', 'Pantry')], default='pantry', max_length=20)),
                ('features', models.ManyToManyField(to='core.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness_pct', models.FloatField()),
                ('pct_full_on_arrival', models.FloatField()),
                ('pct_full_on_departure', models.FloatField()),
                ('photo', models.URLField(max_length=500, null=True)),
                ('restock_date', models.DateField(db_index=True)),
                ('reporter_name', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('needs', models.ManyToManyField(to='core.item')),
                ('pantry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pantry')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person')),
            ],
            options={
                'get_latest_by': 'restock_date',
            },
        ),
        migrations.AddField(
            model_name='pantry',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.person'),
        ),
        migrations.CreateModel(
            name='FoodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500, null=True)),
                ('name', models.CharField(max_length=50)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('food_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foodbank')),
                ('pantries', models.ManyToManyField(to='core.pantry')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
        migrations.AddIndex(
            model_name='restock',
            index=models.Index(fields=['pantry', 'restock_date'], name='core_restoc_pantry__010a2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryroute',
            unique_together={('food_bank', 'date', 'name')},
        ),
    ]
