# Generated by Django 4.0.4 on 2022-04-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
CREATE VIEW estimated_pantry_status AS (
  SELECT
    core_pantry.id AS pantry_id,
    last_restock.restock_date AS last_restock_date,
    last_restock.pct_full_on_departure AS last_pct_full,
    (
      SELECT avg(pct_full_on_arrival)
      FROM core_restock
      WHERE pantry_id = core_pantry.id AND restock_date > current_date - '3 months'::interval
    ) AS avg_pct_full,
    greatest(coalesce(
      pct_full_on_departure - (deplete_pct_per_day * restock_days_ago),
    0::double precision), 0.0::double precision) AS est_pct_full
  FROM core_pantry
  LEFT JOIN LATERAL (
    SELECT
      restock_date,
      pct_full_on_departure,
      (extract(epoch FROM current_timestamp) - extract(epoch FROM restock_date))
        / (60*60*24) AS restock_days_ago
    FROM core_restock WHERE pantry_id = core_pantry.id ORDER BY restock_date DESC LIMIT 1
  ) AS last_restock ON 1=1
)
        """, "DROP VIEW estimated_pantry_status")
    ]
